version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_teste
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data